[features]
seeds = false
skip-lint = false

[programs.localnet]
clicker = "Gbfg24vZ7pfr9zZAixC4aXxt6JB5X1zYwSpQXBAvYL4t"

[programs.devnet]
clicker = "Gbfg24vZ7pfr9zZAixC4aXxt6JB5X1zYwSpQXBAvYL4t"

[programs.mainnet]
clicker = "Gbfg24vZ7pfr9zZAixC4aXxt6JB5X1zYwSpQXBAvYL4t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"